from __future__ import annotations

from datetime import datetime
from typing import Any, Annotated, Literal
from urllib.parse import urlparse
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, model_validator


def _is_absolute_iri(value: str) -> bool:
    parsed = urlparse(value)
    return bool(parsed.scheme and (parsed.netloc or parsed.scheme == "mailto"))


Iri = Annotated[str, Field(min_length=1)]
LanguageMap = dict[str, str]


class XapiModel(BaseModel):
    # Unknown xAPI properties are preserved even though this MVP validates only
    # the subset generated by its Sender.
    model_config = ConfigDict(extra="allow")


class Agent(XapiModel):
    objectType: Literal["Agent"] = "Agent"
    name: str | None = None
    mbox: str

    @model_validator(mode="after")
    def validate_mbox(self) -> Agent:
        if not self.mbox.startswith("mailto:") or "@" not in self.mbox[7:]:
            raise ValueError("actor.mbox must be a mailto IRI")
        return self


class Verb(XapiModel):
    id: Iri
    display: LanguageMap | None = None

    @model_validator(mode="after")
    def validate_id(self) -> Verb:
        if not _is_absolute_iri(self.id):
            raise ValueError("verb.id must be an absolute IRI")
        return self


class ActivityDefinition(XapiModel):
    name: LanguageMap | None = None
    description: LanguageMap | None = None
    type: Iri | None = None

    @model_validator(mode="after")
    def validate_type(self) -> ActivityDefinition:
        if self.type is not None and not _is_absolute_iri(self.type):
            raise ValueError("object.definition.type must be an absolute IRI")
        return self


class Activity(XapiModel):
    objectType: Literal["Activity"] = "Activity"
    id: Iri
    definition: ActivityDefinition | None = None

    @model_validator(mode="after")
    def validate_id(self) -> Activity:
        if not _is_absolute_iri(self.id):
            raise ValueError("object.id must be an absolute IRI")
        return self


class Score(XapiModel):
    scaled: float | None = Field(default=None, ge=-1, le=1)
    raw: float | None = None
    min: float | None = None
    max: float | None = None

    @model_validator(mode="after")
    def validate_range(self) -> Score:
        if self.min is not None and self.max is not None and self.min > self.max:
            raise ValueError("result.score.min must not exceed max")
        if self.raw is not None and self.min is not None and self.raw < self.min:
            raise ValueError("result.score.raw must not be below min")
        if self.raw is not None and self.max is not None and self.raw > self.max:
            raise ValueError("result.score.raw must not exceed max")
        return self


class Result(XapiModel):
    success: bool | None = None
    completion: bool | None = None
    score: Score | None = None
    response: str | None = None


class Context(XapiModel):
    platform: str | None = None
    language: str | None = None
    extensions: dict[str, Any] | None = None

    @model_validator(mode="after")
    def validate_extension_keys(self) -> Context:
        for key in self.extensions or {}:
            if not _is_absolute_iri(key):
                raise ValueError("context extension keys must be absolute IRIs")
        return self


class Statement(XapiModel):
    id: UUID = Field(default_factory=uuid4)
    actor: Agent
    verb: Verb
    object: Activity
    result: Result | None = None
    context: Context | None = None
    timestamp: datetime | None = None

    @model_validator(mode="after")
    def validate_timestamp(self) -> Statement:
        if self.timestamp is not None and self.timestamp.tzinfo is None:
            raise ValueError("timestamp must include a timezone")
        return self
